# Generated by Django 5.1.6 on 2025-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_consulta_confirmada_alter_consulta_id_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='confirmada',
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('A', 'Agendada'), ('C', 'Cancelada'), ('M', 'Confirmada'), ('R', 'Realizada')], default='A', max_length=1),
        ),
    ]
