# Generated by Django 5.1.6 on 2025-03-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_remove_consulta_confirmada_consulta_observacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='data',
            new_name='agendamento',
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sistema.especialidade'),
        ),
    ]
