# Generated by Django 5.1.6 on 2025-04-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_rename_data_consulta_agendamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade',
            new_name='especialidade_id',
        ),
    ]
