# Generated by Django 5.1.6 on 2025-04-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_rename_especialidade_medico_especialidade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sistema.especialidade', verbose_name='Especialidade'),
        ),
    ]
